version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: devops_postgres
    environment:
      POSTGRES_USER: devops_user
      POSTGRES_PASSWORD: super_secret_password
      POSTGRES_DB: todo_db
    # 🔒 SECCIÓN PORTS ELIMINADA: La base de datos ya no expone el puerto 5432 al host/internet.
    # Solo es accesible por los miembros de 'devops_network'.
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - devops_network

  api_app:
    build:
      context: .              # 📂 Ajustado a la raíz para gestionar rutas globales
      dockerfile: app/Dockerfile
    container_name: devops_api
    ports:
      - "8000:8000"           # Solo la API expone tráfico hacia el exterior
    environment:
      - DATABASE_URL=postgresql://devops_user:super_secret_password@postgres_db:5432/todo_db
    depends_on:
      - postgres_db
    networks:
      - devops_network

volumes:
  postgres_data:

networks:
  devops_network:
    driver: bridge            # Red única y aislada para la intercomunicación segura
